spring:
  application:
    name: spring-rag-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        chat:
          include: true
          options:
            format: json
